/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Threads.Carro1;
import Threads.Carro2;
import Threads.Carro3;
import Threads.Carro4;
import Threads.Carro5;
import Threads.Carro6;

/**
 *
 * @author R2
 */
public class FrmMapa extends FrmBase {

    /**
     * Creates new form FrmMapa
     */
    public FrmMapa() {
        initComponents();
        adaptarPantalla();
        moverCarros();
    }
    
    public void moverCarros(){
        Carro1 carro1 = new Carro1(btnMinera1, jPanel1);
        carro1.start();
        Carro2 carro2 = new Carro2(btnMinera2, jPanel1);
        carro2.start();
        Carro3 carro3 = new Carro3(btnMinera3, jPanel1);
        carro3.start();
        Carro4 carro4 = new Carro4(btnMinera4, jPanel1);
        carro4.start();
        Carro5 carro5 = new Carro5(btnMinera5, jPanel1);
        carro5.start();
        Carro6 carro6 = new Carro6(btnMinera6, jPanel1);
        carro6.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnNotificaciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHabilitar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnMinera1 = new javax.swing.JButton();
        btnMinera2 = new javax.swing.JButton();
        btnMinera3 = new javax.swing.JButton();
        btnMinera4 = new javax.swing.JButton();
        btnMinera5 = new javax.swing.JButton();
        btnMinera6 = new javax.swing.JButton();
        btnSemaforo1 = new javax.swing.JButton();
        btnSemaforo2 = new javax.swing.JButton();
        btnSemaforo3 = new javax.swing.JButton();
        btnSemaforo4 = new javax.swing.JButton();
        btnSemaforo5 = new javax.swing.JButton();
        btnSemaforo6 = new javax.swing.JButton();
        btnSemaforo7 = new javax.swing.JButton();
        btnSemaforo8 = new javax.swing.JButton();
        btnSemaforo9 = new javax.swing.JButton();
        btnSemaforo10 = new javax.swing.JButton();
        btnSemaforo11 = new javax.swing.JButton();
        Mapa_Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapa");
        setMinimumSize(new java.awt.Dimension(908, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnMenu.setText("Volver menú");
        btnMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        btnMenu.setContentAreaFilled(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenu);
        btnMenu.setBounds(20, 420, 91, 23);

        btnNotificaciones.setForeground(new java.awt.Color(0, 0, 255));
        btnNotificaciones.setText("Notificaciones");
        btnNotificaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        btnNotificaciones.setContentAreaFilled(false);
        btnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnNotificaciones);
        btnNotificaciones.setBounds(10, 10, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mapa Icon.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(150, -30, 240, 240);

        jLabel2.setText("ID:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 270, 30, 20);

        TxtID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jPanel2.add(TxtID);
        TxtID.setBounds(90, 270, 260, 20);

        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(90, 310, 260, 20);

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel2.add(txtNombre);
        txtNombre.setBounds(90, 240, 260, 20);

        jLabel3.setText("Ubicación:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 310, 60, 14);

        jLabel4.setText("Nombre:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 240, 50, 14);

        btnHabilitar.setText("Habilitar");
        btnHabilitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnHabilitar.setContentAreaFilled(false);
        jPanel2.add(btnHabilitar);
        btnHabilitar.setBounds(90, 360, 120, 30);

        btnDeshabilitar.setText("Deshabilitar");
        btnDeshabilitar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        btnDeshabilitar.setContentAreaFilled(false);
        jPanel2.add(btnDeshabilitar);
        btnDeshabilitar.setBounds(230, 360, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 450, 450);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setMinimumSize(new java.awt.Dimension(706, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera1.setToolTipText("");
        btnMinera1.setBorder(null);
        btnMinera1.setBorderPainted(false);
        btnMinera1.setContentAreaFilled(false);
        btnMinera1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 48.png"))); // NOI18N
        jPanel1.add(btnMinera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, 40));

        btnMinera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera2.setToolTipText("");
        btnMinera2.setBorder(null);
        btnMinera2.setBorderPainted(false);
        btnMinera2.setContentAreaFilled(false);
        btnMinera2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 48.png"))); // NOI18N
        btnMinera2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinera2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 40, 40));

        btnMinera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera3.setToolTipText("");
        btnMinera3.setBorder(null);
        btnMinera3.setBorderPainted(false);
        btnMinera3.setContentAreaFilled(false);
        btnMinera3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 48.png"))); // NOI18N
        btnMinera3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinera3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 40, 40));

        btnMinera4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera4.setToolTipText("");
        btnMinera4.setBorder(null);
        btnMinera4.setBorderPainted(false);
        btnMinera4.setContentAreaFilled(false);
        btnMinera4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 48.png"))); // NOI18N
        btnMinera4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinera4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinera4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 40, 40));

        btnMinera5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera5.setToolTipText("");
        btnMinera5.setBorder(null);
        btnMinera5.setBorderPainted(false);
        btnMinera5.setContentAreaFilled(false);
        btnMinera5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 48.png"))); // NOI18N
        btnMinera5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinera5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinera5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 40, 40));

        btnMinera6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera6.setToolTipText("");
        btnMinera6.setBorder(null);
        btnMinera6.setBorderPainted(false);
        btnMinera6.setContentAreaFilled(false);
        btnMinera6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 icon.png"))); // NOI18N
        btnMinera6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/183233 48.png"))); // NOI18N
        btnMinera6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinera6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinera6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 40, 40));

        btnSemaforo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo1.setBorder(null);
        btnSemaforo1.setBorderPainted(false);
        btnSemaforo1.setContentAreaFilled(false);
        btnSemaforo1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 40, -1));

        btnSemaforo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo2.setBorder(null);
        btnSemaforo2.setBorderPainted(false);
        btnSemaforo2.setContentAreaFilled(false);
        btnSemaforo2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 40, -1));

        btnSemaforo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo3.setBorder(null);
        btnSemaforo3.setBorderPainted(false);
        btnSemaforo3.setContentAreaFilled(false);
        btnSemaforo3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 40, -1));

        btnSemaforo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo4.setBorder(null);
        btnSemaforo4.setBorderPainted(false);
        btnSemaforo4.setContentAreaFilled(false);
        btnSemaforo4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, -1));

        btnSemaforo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo5.setBorder(null);
        btnSemaforo5.setBorderPainted(false);
        btnSemaforo5.setContentAreaFilled(false);
        btnSemaforo5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 40, -1));

        btnSemaforo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo6.setBorder(null);
        btnSemaforo6.setBorderPainted(false);
        btnSemaforo6.setContentAreaFilled(false);
        btnSemaforo6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, -1));

        btnSemaforo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo7.setBorder(null);
        btnSemaforo7.setBorderPainted(false);
        btnSemaforo7.setContentAreaFilled(false);
        btnSemaforo7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 40, -1));

        btnSemaforo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo8.setBorder(null);
        btnSemaforo8.setBorderPainted(false);
        btnSemaforo8.setContentAreaFilled(false);
        btnSemaforo8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, -1));

        btnSemaforo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo9.setBorder(null);
        btnSemaforo9.setBorderPainted(false);
        btnSemaforo9.setContentAreaFilled(false);
        btnSemaforo9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 40, -1));

        btnSemaforo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo10.setBorder(null);
        btnSemaforo10.setBorderPainted(false);
        btnSemaforo10.setContentAreaFilled(false);
        btnSemaforo10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 40, -1));

        btnSemaforo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo11.setBorder(null);
        btnSemaforo11.setBorderPainted(false);
        btnSemaforo11.setContentAreaFilled(false);
        btnSemaforo11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 54.png"))); // NOI18N
        btnSemaforo11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Semaforo icon 60.png"))); // NOI18N
        jPanel1.add(btnSemaforo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, -1));

        Mapa_Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/planosMapa.png"))); // NOI18N
        jPanel1.add(Mapa_Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(453, 0, 540, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.setVisible(false);
        this.getInstanciaFrmMenu().setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesActionPerformed
        this.setVisible(false);
        this.getInstanciaFrmNotificaciones().setVisible(true);
    }//GEN-LAST:event_btnNotificacionesActionPerformed

    private void btnMinera2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinera2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinera2ActionPerformed

    private void btnMinera3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinera3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinera3ActionPerformed

    private void btnMinera4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinera4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinera4ActionPerformed

    private void btnMinera5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinera5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinera5ActionPerformed

    private void btnMinera6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinera6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinera6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mapa_Fond;
    private javax.swing.JTextField TxtID;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMinera1;
    private javax.swing.JButton btnMinera2;
    private javax.swing.JButton btnMinera3;
    private javax.swing.JButton btnMinera4;
    private javax.swing.JButton btnMinera5;
    private javax.swing.JButton btnMinera6;
    private javax.swing.JButton btnNotificaciones;
    private javax.swing.JButton btnSemaforo1;
    private javax.swing.JButton btnSemaforo10;
    private javax.swing.JButton btnSemaforo11;
    private javax.swing.JButton btnSemaforo2;
    private javax.swing.JButton btnSemaforo3;
    private javax.swing.JButton btnSemaforo4;
    private javax.swing.JButton btnSemaforo5;
    private javax.swing.JButton btnSemaforo6;
    private javax.swing.JButton btnSemaforo7;
    private javax.swing.JButton btnSemaforo8;
    private javax.swing.JButton btnSemaforo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
