/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author R2
 */
public class FrmMenu extends FrmBase {

    
    private static FrmLogin frmLogin;
    
    private static FrmReporteMaterial frmReporteMaterial;
    private static FrmMapa frmMapa;
    
    /**
     * Creates new form FrameMenu
     */
    public FrmMenu() {
        initComponents();
        adaptarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        btnNotificaciones = new javax.swing.JButton();
        btnReporteMaterial = new javax.swing.JButton();
        btnMapa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnNotificaciones.setText("Notificaciones");
        btnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesActionPerformed(evt);
            }
        });

        btnReporteMaterial.setText("Reporte Material");
        btnReporteMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteMaterialActionPerformed(evt);
            }
        });

        btnMapa.setText("Mapa");
        btnMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(btnReporteMaterial)
                        .addGap(114, 114, 114)
                        .addComponent(btnMapa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnCerrarSesion)
                        .addGap(99, 99, 99)
                        .addComponent(btnNotificaciones)))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotificaciones)
                    .addComponent(btnCerrarSesion))
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteMaterial)
                    .addComponent(btnMapa))
                .addContainerGap(435, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.setVisible(false);
        getFrmLogin().setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesActionPerformed
        this.setVisible(false);
        this.getInstanciaFrmNotificaciones().setVisible(true);
    }//GEN-LAST:event_btnNotificacionesActionPerformed

    private void btnReporteMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMaterialActionPerformed
        this.setVisible(false);
        getFrmReporteMaterial().setVisible(true);
    }//GEN-LAST:event_btnReporteMaterialActionPerformed

    private void btnMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaActionPerformed
        this.setVisible(false);
        getFrmMapa().setVisible(true);
    }//GEN-LAST:event_btnMapaActionPerformed

    public static FrmLogin getFrmLogin(){
        if (frmLogin == null) {
            frmLogin = new FrmLogin();
        }
        return frmLogin;
    }
    
//    public static FrmRegistroReporte getFrmRegistroReporte(){
//        if (frmRegistroReporte == null) {
//            frmRegistroReporte = new FrmRegistroReporte();
//        }
//        return frmRegistroReporte;
//    }
    
    public static FrmReporteMaterial getFrmReporteMaterial(){
        if (frmReporteMaterial == null) {
            frmReporteMaterial = new FrmReporteMaterial();
        }
        return frmReporteMaterial;
    }
    
    public static FrmMapa getFrmMapa(){
        if (frmMapa == null) {
            frmMapa = new FrmMapa();
        }
        return frmMapa;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMapa;
    private javax.swing.JButton btnNotificaciones;
    private javax.swing.JButton btnReporteMaterial;
    // End of variables declaration//GEN-END:variables
}
